### ISSUE TITLE
Add support to store notary trusts

### ISSUE THREAD

**Issue by marcosnils** [mbentley/docker-trustdtr#1]
In order for content trust to work with the certificate, it needs to be copied also to ~/.docker/tls/<dtr_domain>

**Comment by mbentley** [comment]
Correct; for the notary client to trust the self-signed certificate, it would require that is be trusted on the client performing the signing.  In an ideal situation, you'd front a v2 registry and notary with something like nginx or haproxy so you aren't needing to specify a notary server for Docker Content Trust as the client will look for a notary server at the same location as your registry by default.

**Comment by marcosnils** [comment]
Correct. I was following DTR content trust tutorials and I came with this problem when setting up everything locally. I also found the solution in the docker github issues. It'd be nice if the documentation is updated to users don't face this problem.
